"""Adversarial testing: try to make the strategy lose.

A backtest that looks great proves almost nothing - the market it ran on was
generated by assumptions the strategy may simply be reading back.  The useful
question is the inverse one: *under what conditions does this break?*

Each scenario below removes one crutch or adds one real-world cost:

* ``random_walk``   - drift and regime persistence stripped out.  A trend
  follower has nothing to follow here, so anything it still "earns" was an
  artefact of the generator, not an edge.  **This is the most important test in
  the file**: a strategy that stays profitable on a driftless random walk after
  fees is almost always reading the future somewhere.
* ``whipsaw``       - regimes flip constantly; punishes slow trend logic.
* ``high_fees``     - a 20bp taker fee, i.e. a retail tier or a bad venue.
* ``thin_book``     - wide spreads, shallow depth, heavy impact.
* ``flash_crash``   - frequent violent jumps that gap straight through stops.
* ``brutal``        - every hostile setting at once.

Passing all of these does not mean the strategy makes money live.  Failing any
of them means it definitely will not.
"""

from __future__ import annotations

import statistics
from dataclasses import dataclass, replace
from typing import Callable, Dict, List, Optional

from .backtest import run_backtest
from .data.simulator import MarketSimulator, Regime, SimulatorConfig
from .engine import EngineConfig, TradingEngine
from .execution.broker import ExecutionConfig, PaperBroker
from .risk.manager import RiskConfig, RiskManager
from .strategy.ensemble import default_ensemble

FLAT_REGIMES = [
    Regime("FLAT-A", 0.0, 1.0, 0.5),
    Regime("FLAT-B", 0.0, 1.0, 0.5),
    Regime("FLAT-C", 0.0, 1.0, 0.5),
]
FAST_FLIP = [
    Regime("BULL", 0.0006, 1.0, 0.55),
    Regime("BEAR", -0.0006, 1.0, 0.55),
]


@dataclass
class Scenario:
    key: str
    label: str
    description: str
    sim: Callable[[SimulatorConfig], SimulatorConfig]
    exec: Callable[[ExecutionConfig], ExecutionConfig]

    @staticmethod
    def _id_sim(c: SimulatorConfig) -> SimulatorConfig:
        return c

    @staticmethod
    def _id_exec(c: ExecutionConfig) -> ExecutionConfig:
        return c


SCENARIOS: List[Scenario] = [
    Scenario("baseline", "Baseline", "the default simulated market",
             Scenario._id_sim, Scenario._id_exec),
    Scenario("random_walk", "Random walk", "zero drift, no regime persistence - no trend to find",
             lambda c: replace(c, regimes=list(FLAT_REGIMES), jump_prob=0.002),
             Scenario._id_exec),
    Scenario("whipsaw", "Whipsaw", "regimes flip every few bars",
             lambda c: replace(c, regimes=list(FAST_FLIP)), Scenario._id_exec),
    Scenario("high_fees", "High fees", "20bp taker fee instead of 5bp",
             Scenario._id_sim, lambda c: replace(c, taker_fee_bps=20.0)),
    Scenario("thin_book", "Thin book", "wide spread, shallow depth, heavy impact",
             lambda c: replace(c, spread_bps=6.0, base_liquidity=1.5),
             lambda c: replace(c, half_spread_bps=6.0, impact_coefficient=1.2, latency_bps=2.0)),
    Scenario("flash_crash", "Flash crashes", "frequent violent jumps through stops",
             lambda c: replace(c, jump_prob=0.05, jump_scale=0.05), Scenario._id_exec),
    Scenario("brutal", "Brutal", "no trend + thin book + high fees + jumps, all at once",
             lambda c: replace(c, regimes=list(FLAT_REGIMES), spread_bps=6.0,
                               base_liquidity=1.5, jump_prob=0.03, jump_scale=0.04),
             lambda c: replace(c, taker_fee_bps=20.0, half_spread_bps=6.0,
                               impact_coefficient=1.2, latency_bps=2.0)),
]


@dataclass
class ScenarioResult:
    scenario: Scenario
    returns: List[float]
    win_rates: List[float]
    drawdowns: List[float]
    trades: List[int]

    @property
    def median_return(self) -> float:
        return statistics.median(self.returns) if self.returns else 0.0

    @property
    def worst(self) -> float:
        return min(self.returns) if self.returns else 0.0

    @property
    def best(self) -> float:
        return max(self.returns) if self.returns else 0.0

    @property
    def profitable_share(self) -> float:
        return sum(1 for r in self.returns if r > 0) / len(self.returns) if self.returns else 0.0

    @property
    def median_trades(self) -> float:
        return statistics.median(self.trades) if self.trades else 0.0


def run_scenario(scenario: Scenario, runs: int = 8, bars: int = 3_000,
                 engine_config: Optional[EngineConfig] = None,
                 risk_config: Optional[RiskConfig] = None,
                 base_seed: int = 500) -> ScenarioResult:
    eng_cfg = engine_config or EngineConfig()
    returns, wrs, dds, trades = [], [], [], []
    for i in range(runs):
        sim_cfg = scenario.sim(SimulatorConfig(symbol=eng_cfg.symbol, seed=base_seed + i * 31))
        exec_cfg = scenario.exec(ExecutionConfig(seed=base_seed + i))
        # the scenario's real costs, fed to the risk gate as well as the broker
        rcfg = replace(risk_config or RiskConfig(),
                       round_trip_cost_bps=2 * (exec_cfg.taker_fee_bps + exec_cfg.half_spread_bps))
        engine = TradingEngine(
            eng_cfg,
            ensemble=default_ensemble(),
            risk=RiskManager(rcfg),
            broker=PaperBroker(exec_cfg),
        )
        _, rep = run_backtest(MarketSimulator(sim_cfg, bars=bars).stream(), eng_cfg, engine=engine)
        returns.append(rep.total_return)
        wrs.append(rep.win_rate)
        dds.append(rep.max_drawdown)
        trades.append(rep.trades)
    return ScenarioResult(scenario, returns, wrs, dds, trades)


def run_all(runs: int = 8, bars: int = 3_000, engine_config: Optional[EngineConfig] = None,
            risk_config: Optional[RiskConfig] = None, progress=None) -> List[ScenarioResult]:
    out = []
    for i, sc in enumerate(SCENARIOS):
        if progress:
            progress(i + 1, len(SCENARIOS), sc)
        out.append(run_scenario(sc, runs, bars, engine_config, risk_config))
    return out


def render(results: List[ScenarioResult]) -> str:
    lines = [
        "╔══ STRESS TEST · can this strategy be broken? " + "═" * 32 + "╗",
        f"  {'scenario':<14}{'median':>9}{'worst':>9}{'best':>9}{'win%':>8}{'maxDD':>8}{'trades':>8}   verdict",
        "  " + "─" * 76,
    ]
    for r in results:
        med = r.median_return
        wr = statistics.median(r.win_rates) if r.win_rates else 0.0
        dd = statistics.median(r.drawdowns) if r.drawdowns else 0.0
        if r.median_trades < 1:
            # Refusing to trade when costs swamp the edge is the correct
            # outcome, not a failure - flat beats slowly bleeding to fees.
            verdict = "stood down (costs > edge)"
        elif r.scenario.key == "random_walk":
            # On a driftless walk, the honest expectation is a small loss: you
            # pay fees and spread for no edge.  A *profit* here is suspicious.
            verdict = "SUSPICIOUS - profits without drift" if med > 0.02 else "expected (costs, no edge)"
        elif med > 0:
            verdict = "survives"
        elif med > -0.05:
            verdict = "bleeds slowly"
        else:
            verdict = "BREAKS"
        lines.append(f"  {r.scenario.label:<14}{med*100:>8.2f}%{r.worst*100:>8.2f}%{r.best*100:>8.2f}%"
                     f"{wr*100:>7.1f}%{dd*100:>7.2f}%{r.median_trades:>8.0f}   {verdict}")
    lines.append("  " + "─" * 76)
    for r in results:
        lines.append(f"  {r.scenario.label:<14}{r.scenario.description}")
    lines.append("╚" + "═" * 76 + "╝")
    return "\n".join(lines)
